[common]
platform      = espressif32
board         = esp32-s3-devkitc-1
framework     = arduino
monitor_speed = 115200
monitor_filters = time, send_on_enter
upload_speed  = 115200
build_flags   =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0

[env:test_fingerprint]
extends          = common
build_src_filter = +<fingerprint/*>
lib_deps         = adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0

[env:test_rfid]
extends          = common
build_src_filter = +<rfid/*>
lib_deps         =
    adafruit/Adafruit PN532
    adafruit/Adafruit BusIO

[env:test_audio]
extends                 = common
build_src_filter        = +<audio/*>
board_build.filesystem  = littlefs
lib_deps                = esphome/ESP32-audioI2S @ ^2.0.13

[env:attendance]
extends                 = common
build_src_filter        = +<attendance/**/*>
board_build.filesystem  = littlefs
build_flags      =
    ${common.build_flags}
    -Isrc/attendance
lib_deps         =
    adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0
    adafruit/Adafruit PN532
    adafruit/Adafruit BusIO
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson @ ^7.0.0
